# Generated by Django 4.1.1 on 2022-10-08 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adgroup_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=64)),
                ('adgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads_Generator.adgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdTextTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adtext_template_headline_1', models.CharField(max_length=64)),
                ('adtext_template_headline_2', models.CharField(max_length=64)),
                ('adtext_template_description_1', models.CharField(max_length=128)),
                ('adtext_template_description_2', models.CharField(max_length=128)),
                ('campaign', models.ManyToManyField(blank=True, to='Ads_Generator.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adtext_headline_1', models.CharField(max_length=64)),
                ('adtext_headline_2', models.CharField(max_length=64)),
                ('adtext_description_1', models.CharField(max_length=128)),
                ('adtext_description_2', models.CharField(max_length=128)),
                ('adgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads_Generator.adgroup')),
            ],
        ),
        migrations.AddField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads_Generator.campaign'),
        ),
    ]
