# Generated by Django 4.1.1 on 2022-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads_Generator', '0002_campaign_user-campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtext',
            name='adtext_description_1',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='adtext',
            name='adtext_description_2',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='adtext',
            name='adtext_headline_1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='adtext',
            name='adtext_headline_2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='adtexttemplate',
            name='adtext_template_description_1',
            field=models.CharField(max_length=270),
        ),
        migrations.AlterField(
            model_name='adtexttemplate',
            name='adtext_template_description_2',
            field=models.CharField(max_length=270),
        ),
        migrations.AlterField(
            model_name='adtexttemplate',
            name='adtext_template_headline_1',
            field=models.CharField(max_length=810),
        ),
        migrations.AlterField(
            model_name='adtexttemplate',
            name='adtext_template_headline_2',
            field=models.CharField(max_length=810),
        ),
    ]
