# Generated by Django 4.1.1 on 2022-11-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads_Generator', '0003_alter_adtext_adtext_description_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtexttemplate',
            name='adtext_template_description_1',
            field=models.CharField(max_length=810),
        ),
        migrations.AlterField(
            model_name='adtexttemplate',
            name='adtext_template_description_2',
            field=models.CharField(max_length=810),
        ),
        migrations.AlterField(
            model_name='adtexttemplate',
            name='adtext_template_headline_1',
            field=models.CharField(max_length=270),
        ),
        migrations.AlterField(
            model_name='adtexttemplate',
            name='adtext_template_headline_2',
            field=models.CharField(max_length=270),
        ),
    ]
